/**
 * State definition for Jira Audio Quote workflow
 */

import { BaseWorkflowState } from '../../types/workflow';

export interface JiraAudioQuoteState extends BaseWorkflowState {
  // Input parameters
  summary: string;
  description: string;
  projectKey: string;

  // Optional inputs
  context?: string; // Context for quote enhancement

  // Generated/returned from Claude during resume
  atlassianPrompt?: string;
  quote?: string; // Generated by atlassian-prompts, returned on resume
  ticketKey?: string; // Created via Playwright, returned on resume
  ticketUrl?: string; // Created via Playwright, returned on resume

  // Generated by sub-agent
  enhancedQuote?: string;
  voiceDirections?: string;

  // Generated by ElevenLabs
  audioId?: string;
  audioPath?: string;

  // Resuming flag
  resuming?: boolean;
}
